# Generated by Django 3.2.5 on 2021-10-21 06:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblbookseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Book Series',
                'db_table': 'tblbookseries',
            },
        ),
        migrations.CreateModel(
            name='tblchapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
            ],
            options={
                'verbose_name': 'Chapter',
                'db_table': 'tblchapter',
            },
        ),
        migrations.CreateModel(
            name='tblclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
            ],
            options={
                'verbose_name': 'Class',
                'db_table': 'tblclass',
            },
        ),
        migrations.CreateModel(
            name='tblsubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Subject',
                'db_table': 'tblsubject',
            },
        ),
        migrations.AddConstraint(
            model_name='tblsubject',
            constraint=models.UniqueConstraint(fields=('name',), name='tblsubject'),
        ),
        migrations.AddField(
            model_name='tblchapter',
            name='bookseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tblbookseries'),
        ),
        migrations.AddField(
            model_name='tblchapter',
            name='classid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tblclass'),
        ),
        migrations.AddField(
            model_name='tblchapter',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tblsubject'),
        ),
        migrations.AddField(
            model_name='tblbookseries',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.tblsubject', validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
